from .convnext import *
from .mlp_mixer import *
from .swin_transformer import *
from .vision_transformer import *

from .doit1 import *
from .doit2 import *
from .doit3 import *
from .doit4 import *
from .doit5 import *
from .doit6 import *
from .doit6_test import *
from .doit7 import *
from .doit8 import *
from .doit8_test import *
from .doit9 import *
from .doit10 import *
from .doit11 import *
from .doit12 import *
from .doit13 import *
from .doit14 import *
from .doit15 import *
from .doit16 import *
from .doit17 import *
from .doit18 import *
from .doit19 import *
from .doit20 import *
from .doit21 import *
from .doit22 import *
from .doit22_hr import *
from .doit22_quant import *